
// Mint addresses generated by init-tokens.ts
export const TEST_TOKENS = {
    GOLD_MINT: "8xg1mwpBJoorBQqmxNDTcAanBt9LWsnDgYPzEXaAk2vG",
    GEMS_MINT: "41qxcfvUo6sG4ZDrDhtdKg8FGebmXE63c4GcYRQcp4a6",
    ARCHER_MINT: "5wm3uu8H3E6b7D85xRDJFZhVZ5F5TC7MDxqVL5r9Nro6"
};
