
// Mint addresses generated by init-tokens.ts
export const TEST_TOKENS = {
    GOLD_MINT: "96nBkev5CpLvGzHqrw68KPBR1SePKEMGmTPLquUQgeut",
    GEMS_MINT: "3SahXoeDAyVWhfbeLqKnVxAA1ytXJKHTgyKwiSoemyHF",
    ARCHER_MINT: "9fMb16cG7UZ6wbRXnp8yendK6qD87Ks6CnjrdhwRSZs"
};
